# This file contains all the important configuration details about this application/microservice

# 1. JPA -> contains all the necessary info for JPA settings of this project.
# -> Determines how Hibernate manages your database schema on application startup
# for ex. update -> Automatically adds new columns or tables based when your entity changes on each restart

# 2. Datasource Config -> contains all the necessary info regarding your DB like its url,username,password etc.
# -> All Spring does is visits tha URl and use username & p/w provided to pass authentication and perform the asked operation on DB based on JPA settings.

# 3. Server Config -> contains configuration for our local host
# -> port :8081,8080,9000 -> tells on which port we'll host our web app(means where tomcat will listen for requests).


#App Info -> tells spring about the name of project
spring.application.name=UserAuthService

# Set the application's base URL context path prefix
# IRL URL breakdown ->
# Protocol(https)+ Domain(amazon.com) + GatewayRouting(/v1){API Gateway route to version1/2 of the service} + ContextPath(/user){usually service name} + ServletPath(/login){the endpoint} + PathInfo(/1){Path Variables} + QueryParams
# In actual production systems url is designed later so for testing we hardcode it like this but later move it to env variable.
# This can now be moved to an environment variable.
server.servlet.context-path=/user

#Datasource Config
#Connection URL
spring.datasource.url=${datasource_url}
#Database credentials
spring.datasource.username=${datasource_username}
#spring.datasource.password=secret


#Server Config
server.port=8081


#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#Secret Key
jwt.secret_key =${jwt_secret_key}